In [68]:
import pandas as pd
import numpy as np
  #              MAKING THE DATA FRAME 
data = {
    "name": [
        "Aarav", "Aditi", "Rohan", "Sneha", "Vikram", 
        "Pooja", "Karan", "Neha", "Arjun", "Priya", 
        "Rahul", "Ananya", "Aditya", "Kavya", "Manish", 
        "Shruti", "Siddharth", "Nisha", "Rohit", "Riya", 
        "Amit", "Kiran", "Deepak", "Meera", "Sanjay"
    ],
    "age": [
        28, 25, 32, 27, 40, 
        29, 35, 31, 26, 24, 
        38, 28, 45, 33, 30, 
        27, 42, 29, 36, 25, 
        31, 34, 48, 26, 39
    ],
    "city": [
        "Mumbai", "Bangalore", "Delhi", "Pune", "Hyderabad", 
        "Chennai", "Gurgaon", "Noida", "Bangalore", "Mumbai", 
        "Delhi", "Pune", "Hyderabad", "Chennai", "Gurgaon", 
        "Noida", "Mumbai", "Bangalore", "Delhi", "Pune", 
        "Hyderabad", "Chennai", "Gurgaon", "Noida", "Bangalore"
    ],
    "salary": [
        850000, 600000, 1200000, 750000, 2100000, 
        900000, 1500000, 1100000, 650000, 500000, 
        1800000, 800000, 2500000, 1300000, 1050000, 
        700000, 2200000, 950000, 1600000, 550000, 
        1150000, 1400000, 2800000, 620000, 1950000
    ]
}
all = pd.DataFrame(data)
all

         name  age       city   salary
0       Aarav   28     Mumbai   850000
1       Aditi   25  Bangalore   600000
2       Rohan   32      Delhi  1200000
3       Sneha   27       Pune   750000
4      Vikram   40  Hyderabad  2100000
5       Pooja   29    Chennai   900000
6       Karan   35    Gurgaon  1500000
7        Neha   31      Noida  1100000
8       Arjun   26  Bangalore   650000
9       Priya   24     Mumbai   500000
10      Rahul   38      Delhi  1800000
11     Ananya   28       Pune   800000
12     Aditya   45  Hyderabad  2500000
13      Kavya   33    Chennai  1300000
14     Manish   30    Gurgaon  1050000
15     Shruti   27      Noida   700000
16  Siddharth   42     Mumbai  2200000
17      Nisha   29  Bangalore   950000
18      Rohit   36      Delhi  1600000
19       Riya   25       Pune   550000
20       Amit   31  Hyderabad  1150000
21      Kiran   34    Chennai  1400000
22     Deepak   48    Gurgaon  2800000
23      Meera   26      Noida   620000
24     Sanjay   39  Bangalore  1950000

In [69]:
#      IN LIST
data = [
    ["Alice", 28, "New York", 75000],
    ["Bob", 34, "London", 82000],
    ["Charlie", 25, "Toronto", 60000],
    ["Diana", 41, "Sydney", 105000]
]
columns = ["Name" , "Age" , "city" , "salary"]
df = pd.DataFrame(data , columns= columns)
df

      Name  Age      city  salary
0    Alice   28  New York   75000
1      Bob   34    London   82000
2  Charlie   25   Toronto   60000
3    Diana   41    Sydney  105000

In [70]:
 # Selction and Indexing of colomuns 
#df['Name']
##df['city']
#df[['Name' , 'Age' , 'city' , 'salary']]

In [71]:
#           CREATE A NEW  COLUMN 
df["desigenation"] = ["Doctor" , "Engg" , "Doctor" , "Engg"]
df

      Name  Age      city  salary desigenation
0    Alice   28  New York   75000       Doctor
1      Bob   34    London   82000         Engg
2  Charlie   25   Toronto   60000       Doctor
3    Diana   41    Sydney  105000         Engg

In [72]:
#           REMOVING THE COLUMN 
# Overwrites the old dataframe with the new, filtered one
df = df.drop(["desigenation"], axis=1 ) # inplace remove the elemnet in your real data
# if you are remove the row you can change the value of axis = 0

In [73]:
df

      Name  Age      city  salary
0    Alice   28  New York   75000
1      Bob   34    London   82000
2  Charlie   25   Toronto   60000
3    Diana   41    Sydney  105000

In [74]:
#           SELECTING ROW 
df.loc[[0,1 ,2]] # loc[] means location

      Name  Age      city  salary
0    Alice   28  New York   75000
1      Bob   34    London   82000
2  Charlie   25   Toronto   60000

In [75]:
#               SELECTING SUBSET ROWS AND COLUMN 
df.loc[[1,2]][["city","salary"]]

      city  salary
1   London   82000
2  Toronto   60000

In [76]:
#                Conditional Selection
high = df[df['salary'] > 70000]
high

    Name  Age      city  salary
0  Alice   28  New York   75000
1    Bob   34    London   82000
3  Diana   41    Sydney  105000

In [78]:
young = df[(df["Age"] < 30 ) & (df["city"] == "New York")]
young

london_sydney = df[(df["city"] == "London") | (df["city"] == "Sydney")]
london_sydney

    Name  Age    city  salary
1    Bob   34  London   82000
3  Diana   41  Sydney  105000