In [9]:
import numpy as np
import pandas as pd 
#                   Finding Missing Data
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
missingData = df.isna().sum() # this is give the number of null data in your data 
missingData

A    1
B    0
C    2
D    3
dtype: int64

In [12]:
checking = df.isin([1 ,2 ,3 ])
checking

       A      B      C      D
0   True   True   True   True
1   True   True   True  False
2  False   True   True  False
3  False  False  False  False
4  False  False  False  False

In [ ]:
df.isna().any()# any means NAN value is exist or not

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
df.dropna()# it is show the that row where the Nan not exit

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df.dropna(thresh=3) # it is remove those row value which is less than 3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [ ]:
#                   Filling the missing Data
df.fillna(0)# it is replace the NAN and fill the 0

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [17]:
values = {"A" : 0 , "B" : 100 , "C" : 200 , "D" : 500}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  500.0
2  0.0  3    3.0  500.0
3  4.0  4  200.0  500.0
4  5.0  5  200.0    5.0

In [18]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [19]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0